### ISSUE TITLE
File input

### ISSUE THREAD

**Issue by saihtunlu** [ThirashaPraween/RearGen#1]
Hi, author. File input isn't working. File picker wasn't appear.

**Comment by ThirashaPraween** [comment]
Hi @saihtunlu!, RearGen generator working with a terminal(CLI). So terminals can't show any file picker dialog. You have to input the file path (with the file extension/format) to relevant places. Also, if you input any wrong file path, RearGen will let you know that. I would recommend following the GitHub readme.md guidelines and check the image below.

![img](https://i.imgur.com/OCJGU97.png)

**Comment by saihtunlu** [comment]
Ohh sorry, I meant input tag in html isn't working.

**Comment by ThirashaPraween** [comment]
Are you generating a website URL app or a new website inside the `src` folder?

**Comment by saihtunlu** [comment]
I've generated with website URL, [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file](url) file choosers are not working, also other website's file choosers too. Eg. upload image to website.

**Comment by ThirashaPraween** [comment]
Okay, I'll check it out. If it is possible, I'll try to fix it and release a new version with file uploading support. Thank you for informing this @saihtunlu.

**Comment by ThirashaPraween** [comment]
Hello @saihtunlu , As per your request, there is some issue with the HTML file input. So just fixed that issue and released a new version. You can download and try it without any file input issue. Thank you for informing that. Also, the file input support only RearGen version 1.7.0 or newer.
