### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lianglee** [ThirashaPraween/RearGen#2]
Does this have ability to encrypt js/html files and a way to get push notification device id?

**Comment by ThirashaPraween** [comment]
I don't know what exactly you mean by encrypting html/css files. But, I think there is no need to encrypt Html/js files if you develop the app inside the `src` folder. That entire `src` folder will convert into app resources automatically by the RearGen terminal. After generating apk or bundle, no one can see those files.

Unfortunately, The RearGen apps have not supported push notifications yet. But in the feature releases, we'll try to implement push notifications and iOS support.

**Comment by lianglee** [comment]
If someone unpacks the apk file will it shows those src files?

**Comment by ThirashaPraween** [comment]
I don't think so, but if it is possible, we can use minifying or obfuscating methods for html, css, and js. https://obfuscator.io is one of the best javascript obfuscating tool.
